export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL_DISMISS_ALERT = 'AUTH_FAIL_DISMISS_ALERT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_CARS_START = 'FETCH_CARS_START';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAIL = 'FETCH_CARS_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const CHECKOUT_INIT = 'CHECKOUT_INIT';
export const CHECKOUT_START = 'CHECKOUT_START';

export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
